# server:
#   port: 8080

# spring:
#   application:
#     name: api-gateway

#   profiles:
#     active: development

#   cloud:

#     gateway:
#       discovery:
#         locator:
#           enabled: true
#       routes:
#         - id: auth-service
#           uri: lb://AUTH-SERVICE
#           predicates:
#             - Path=/auth/**
#         - id: user-service
#           uri: lb://USER-SERVICE
#           predicates:
#             - Path=/users/**

#     config:
#       server:
#         git:
#           search-paths: development

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka




server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka