# spring:
#   application:
#     name: user-service

# server:
#   port: 8080

# user:
#   message: "User service running in PRODUCTION mode"
#   cache:
#     enabled: true



server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://prod-mysql-user:3306/user_db
    username: user_user
    password: user_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka